### ISSUE TITLE
Rendering HTML as opposed to JSON for ajax calls

### ISSUE THREAD

**Issue by priyad** [Wisc-Land-Map-Tool/Wisc-Land-Web-App#4]
**Summary**
Responses to the mobile application are being rendered as HTML instead of JSON.

**Description**
The web application controller needs to respond to mobile ajax requests with JSON data rather than HTML which would be normally sent back for ajax calls from the web. 

**Severity**
Critical

**Comment by j-buckner** [comment]
The mobile login controller under app/controllers/mobile/sessions_controller.rb was modified to respond to json formatted requests and render it's response as json as well.
